local M = {}
M.TITLE = "TITLE"
M.NEW_GAME = "NEW_GAME"
M.INSTRUCTIONS = "INSTRUCTIONS"
M.INSTRUCTIONS2 = "INSTRUCTIONS2"
M.BETWEEN_ROUNDS = "BETWEEN_ROUNDS"
M.NEW_ROUND = "NEW_ROUND"
M.MAKE_GUESS = "MAKE_GUESS"
M.DEAD = "DEAD"
M.SHOPPE = "SHOPPE"
M.INVENTORY = "INVENTORY"
return M